// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Profile } from "./Profile";
import type { Settings } from "./Settings";

export type AppConfig = { version: number, profiles: Array<Profile>, settings: Settings, };
