// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppRule } from "./AppRule";
import type { Layer } from "./Layer";

export type Profile = { name: string, layers: Array<Layer>, app_rules: Array<AppRule>, };
