// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldAction } from "./HoldAction";
import type { KeyRef } from "./KeyRef";

export type Rule = { "type": "simple", from: KeyRef, to: KeyRef, } | { "type": "tap_hold", from: KeyRef, tap: KeyRef, hold: HoldAction, hold_timeout_ms: bigint, };
