// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = { tap_hold_timeout_ms: bigint, emergency_hotkey: string, 
/**
 * When false (default), switching foreground app resets to Base Layer.
 * When true, layer state persists across app switches.
 */
layer_sticky: boolean, };
