# __YORLING_MARKER__
"""Yorling Hermes plugin.

Generated by Yorling. Reinstall from Island settings if you need to refresh it.
"""

from __future__ import annotations

import json
import os
import subprocess
import threading

BRIDGE_BASE_ARGS = json.loads(r'''__BRIDGE_BASE_ARGS_JSON__''')
SESSION_STATE = {}


def _stable_text(value):
    if value is None:
        return None
    if isinstance(value, str):
        stripped = value.strip()
        return stripped or None
    try:
        return json.dumps(value, ensure_ascii=False)
    except Exception:
        return None


def _session_state(session_id):
    if session_id not in SESSION_STATE:
        SESSION_STATE[session_id] = {
            "cwd": None,
            "assistant": None,
            "did_emit_start": False,
            "terminated": False,
        }
    return SESSION_STATE[session_id]


def _session_id(value):
    normalized = _stable_text(value)
    if not normalized:
        return None
    return normalized if normalized.startswith("hermes-") else f"hermes-{normalized}"


def _resolve_session_id(*candidates, **kwargs):
    for candidate in candidates:
        resolved = _session_id(candidate)
        if resolved:
            return resolved
    for key in ("session_id", "task_id", "conversation_id"):
        resolved = _session_id(kwargs.get(key))
        if resolved:
            return resolved
    return None


def _resolve_cwd(kwargs):
    for key in ("cwd", "working_directory", "directory"):
        resolved = _stable_text(kwargs.get(key))
        if resolved:
            return resolved
    try:
        return os.getcwd()
    except OSError:
        return None


def _collect_env():
    env = os.environ.copy()
    if not env.get("TTY"):
        for fd in (0, 1, 2):
            try:
                tty_value = os.ttyname(fd)
            except OSError:
                continue
            if tty_value:
                env["TTY"] = tty_value
                break
    return env


def _bridge_payload(session_id, **payload):
    state = _session_state(session_id)
    cwd = payload.pop("cwd", None) or state.get("cwd")
    if cwd:
        state["cwd"] = cwd
    return {
        "session_id": session_id,
        "cwd": cwd,
        **{key: value for key, value in payload.items() if value is not None},
    }


def _emit(event_name, payload):
    def _worker():
        try:
            process = subprocess.Popen(
                BRIDGE_BASE_ARGS + ["--event", event_name],
                stdin=subprocess.PIPE,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                text=True,
                env=_collect_env(),
                start_new_session=True,
            )
            if process.stdin:
                process.stdin.write(json.dumps(payload, ensure_ascii=False))
                process.stdin.close()
        except Exception:
            return

    threading.Thread(target=_worker, daemon=True).start()


def _extract_user_message(kwargs):
    direct = _stable_text(kwargs.get("user_message"))
    if direct:
        return direct
    for key in ("last_user_message", "prompt", "input", "query", "text", "content", "message"):
        candidate = _stable_text(kwargs.get(key))
        if candidate:
            return candidate
    return None


def _extract_assistant_message(kwargs):
    direct = _stable_text(kwargs.get("assistant_response"))
    if direct:
        return direct
    fallback = _stable_text(kwargs.get("last_assistant_message"))
    if fallback:
        return fallback
    response = kwargs.get("response")
    if isinstance(response, str):
        return _stable_text(response)
    if isinstance(response, dict):
        for key in ("content", "text", "response", "message"):
            candidate = _stable_text(response.get(key))
            if candidate:
                return candidate
    return None


def _parse_tool_result(result):
    if isinstance(result, str):
        try:
            parsed = json.loads(result)
        except Exception:
            return None, None
        if isinstance(parsed, dict):
            return parsed, _stable_text(parsed.get("error"))
        return None, None
    if isinstance(result, dict):
        return result, _stable_text(result.get("error"))
    return None, None


def _emit_session_start(session_id, **payload):
    state = _session_state(session_id)
    if state.get("did_emit_start") or state.get("terminated"):
        return
    _emit("SessionStart", _bridge_payload(session_id, **payload))
    state["did_emit_start"] = True


def _on_session_start(session_id=None, **kwargs):
    resolved = _resolve_session_id(session_id, **kwargs)
    if not resolved:
        return
    state = _session_state(resolved)
    if state.get("terminated"):
        SESSION_STATE[resolved] = {
            "cwd": state.get("cwd"),
            "assistant": state.get("assistant"),
            "did_emit_start": False,
            "terminated": False,
        }
    _emit_session_start(
        resolved,
        cwd=_resolve_cwd(kwargs),
        message=_extract_user_message(kwargs),
    )


def _on_pre_llm_call(session_id=None, user_message=None, **kwargs):
    resolved = _resolve_session_id(session_id, kwargs.get("task_id"), **kwargs)
    if not resolved:
        return None
    prompt = _stable_text(user_message) or _extract_user_message(kwargs)
    cwd = _resolve_cwd(kwargs)
    _emit_session_start(resolved, cwd=cwd, message=prompt)
    if prompt:
        _emit("UserPromptSubmit", _bridge_payload(resolved, prompt=prompt, cwd=cwd))
    return None


def _on_pre_tool_call(tool_name=None, args=None, task_id=None, **kwargs):
    resolved = _resolve_session_id(task_id, kwargs.get("session_id"), **kwargs)
    if not resolved:
        return
    cwd = _resolve_cwd(kwargs)
    _emit_session_start(
        resolved,
        cwd=cwd,
        message=_extract_user_message(kwargs),
    )
    _emit(
        "PreToolUse",
        _bridge_payload(
            resolved,
            tool_name=_stable_text(tool_name) or "Tool",
            tool_input=args if isinstance(args, dict) else None,
            cwd=cwd,
        ),
    )


def _on_post_tool_call(tool_name=None, args=None, result=None, task_id=None, **kwargs):
    resolved = _resolve_session_id(task_id, kwargs.get("session_id"), **kwargs)
    if not resolved:
        return
    parsed_result, error_text = _parse_tool_result(result)
    cwd = _resolve_cwd(kwargs)
    _emit_session_start(
        resolved,
        cwd=cwd,
        message=_extract_user_message(kwargs),
    )
    _emit(
        "PostToolUseFailure" if error_text else "PostToolUse",
        _bridge_payload(
            resolved,
            tool_name=_stable_text(tool_name) or "Tool",
            tool_input=args if isinstance(args, dict) else None,
            tool_result=parsed_result,
            error=error_text,
            cwd=cwd,
        ),
    )


def _on_post_llm_call(session_id=None, assistant_response=None, **kwargs):
    resolved = _resolve_session_id(session_id, kwargs.get("task_id"), **kwargs)
    if not resolved:
        return
    reply = _stable_text(assistant_response) or _extract_assistant_message(kwargs)
    if not reply:
        return
    cwd = _resolve_cwd(kwargs)
    _emit_session_start(
        resolved,
        cwd=cwd,
        message=_extract_user_message(kwargs),
    )
    _session_state(resolved)["assistant"] = reply
    _emit(
        "Notification",
        _bridge_payload(
            resolved,
            notification_type="assistant_message",
            message=reply,
            cwd=cwd,
        ),
    )


def _on_session_end(session_id=None, **kwargs):
    resolved = _resolve_session_id(session_id, kwargs.get("task_id"), **kwargs)
    if not resolved:
        return
    state = _session_state(resolved)
    cwd = _resolve_cwd(kwargs)
    _emit_session_start(
        resolved,
        cwd=cwd,
        message=_extract_user_message(kwargs),
    )
    _emit(
        "Stop",
        _bridge_payload(
            resolved,
            last_assistant_message=state.get("assistant"),
            cwd=cwd,
        ),
    )


def _on_session_finalize(session_id=None, **kwargs):
    resolved = _resolve_session_id(session_id, kwargs.get("task_id"), **kwargs)
    if not resolved:
        return
    state = _session_state(resolved)
    cwd = _resolve_cwd(kwargs)
    _emit_session_start(
        resolved,
        cwd=cwd,
        message=_extract_user_message(kwargs),
    )
    _emit(
        "SessionEnd",
        _bridge_payload(
            resolved,
            last_assistant_message=state.get("assistant"),
            cwd=cwd,
        ),
    )
    state["terminated"] = True


def _on_session_reset(session_id=None, **kwargs):
    resolved = _resolve_session_id(session_id, kwargs.get("task_id"), **kwargs)
    if not resolved:
        return
    _emit_session_start(
        resolved,
        cwd=_resolve_cwd(kwargs),
        message=_extract_user_message(kwargs),
    )


def register(ctx):
    ctx.register_hook("on_session_start", _on_session_start)
    ctx.register_hook("pre_llm_call", _on_pre_llm_call)
    ctx.register_hook("pre_tool_call", _on_pre_tool_call)
    ctx.register_hook("post_tool_call", _on_post_tool_call)
    ctx.register_hook("post_llm_call", _on_post_llm_call)
    ctx.register_hook("on_session_end", _on_session_end)
    ctx.register_hook("on_session_finalize", _on_session_finalize)
    ctx.register_hook("on_session_reset", _on_session_reset)
