// __YORLING_MARKER__
// Generated by Yorling. Reinstall from Island settings if you need to refresh it.

const BRIDGE_BASE_ARGS = __BRIDGE_BASE_ARGS_JSON__;

function stableString(value: unknown): string | undefined {
  if (value == null) return undefined;
  if (typeof value === 'string') {
    const trimmed = value.trim();
    return trimmed.length > 0 ? trimmed : undefined;
  }
  try {
    return JSON.stringify(value);
  } catch {
    return undefined;
  }
}

function firstDefined<T>(...values: T[]): T | undefined {
  for (const value of values) {
    if (value !== undefined && value !== null && value !== '') {
      return value;
    }
  }
  return undefined;
}

function summarizeContent(content: unknown): string | undefined {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    const parts = content.map((entry) => summarizeContent(entry)).filter(Boolean);
    return parts.length > 0 ? parts.join('\n') : undefined;
  }
  if (content && typeof content === 'object') {
    const record = content as Record<string, unknown>;
    return firstDefined(
      summarizeContent(record.text),
      summarizeContent(record.body),
      summarizeContent(record.message),
      stableString(content),
    );
  }
  return undefined;
}

function titleFor(event: any): string {
  return (
    firstDefined(
      event?.context?.sessionEntry?.title,
      event?.context?.sessionEntry?.name,
      event?.context?.patch?.title,
      'OpenClaw',
    ) ?? 'OpenClaw'
  );
}

function previewFor(event: any): string | undefined {
  return firstDefined(
    summarizeContent(event?.context?.content),
    summarizeContent(event?.context?.bodyForAgent),
    summarizeContent(event?.context?.transcript),
    summarizeContent(event?.context?.patch),
    stableString(event?.context?.commandSource),
    stableString(`${event?.type ?? 'event'}:${event?.action ?? 'unknown'}`),
  );
}

function mapHookEvent(event: any): string | undefined {
  const key = `${event?.type ?? ''}:${event?.action ?? ''}`;
  switch (key) {
    case 'command:new':
      return 'SessionStart';
    case 'command:reset':
      return previewFor(event) ? 'UserPromptSubmit' : 'SessionStart';
    case 'message:sent':
      return 'UserPromptSubmit';
    case 'message:received':
      return 'AgentResponse';
    case 'session:compact:before':
      return 'PreCompact';
    case 'command:stop':
      return 'Stop';
    case 'session:compact:after':
    case 'session:patch':
      return 'Notification';
    default:
      return 'Notification';
  }
}

function buildPayload(event: any) {
  const rawSessionId = firstDefined(
    event?.context?.sessionEntry?.id,
    event?.context?.sessionEntry?.sessionID,
    event?.context?.sessionEntry?.sessionId,
    event?.context?.patch?.sessionID,
    event?.context?.patch?.sessionId,
    event?.sessionKey,
    event?.sessionID,
    event?.sessionId,
    event?.context?.sessionKey,
    event?.context?.sessionID,
    event?.context?.sessionId,
  );
  const sessionId = stableString(rawSessionId);
  if (!sessionId) {
    return null;
  }

  const message = previewFor(event);
  const hookEventName = mapHookEvent(event);
  if (!hookEventName) {
    return null;
  }

  const payload = {
    hook_event_name: hookEventName,
    session_id: sessionId,
    transcript_path: `${process.env.HOME ?? ''}/.openclaw/agents/main/sessions/${sessionId}.jsonl`,
    cwd: firstDefined(
      event?.context?.workspaceDir,
      event?.context?.workspace?.dir,
      event?.context?.directory,
      event?.context?.sessionEntry?.workspaceDir,
      event?.context?.sessionEntry?.directory,
      event?.context?.cfg?.workspace?.dir,
    ),
    event: `${event?.type ?? 'unknown'}:${event?.action ?? 'unknown'}`,
    title: titleFor(event),
    message,
  };

  return Object.fromEntries(
    Object.entries(payload).filter(([, value]) => value !== undefined && value !== null && value !== ''),
  );
}

async function forwardViaNode(payload: Record<string, unknown>, hookEventName: string) {
  const { spawn } = await import('node:child_process');
  return await new Promise((resolve, reject) => {
    const child = spawn(BRIDGE_BASE_ARGS[0], [...BRIDGE_BASE_ARGS.slice(1), '--event', hookEventName], {
      stdio: ['pipe', 'ignore', 'ignore'],
      env: process.env,
    });
    child.once('error', reject);
    child.once('close', (code, signal) => resolve({ code, signal }));
    child.stdin.on('error', () => {});
    child.stdin.write(JSON.stringify(payload));
    child.stdin.end();
  });
}

const handler = async (event: any) => {
  const payload = buildPayload(event);
  if (!payload) return;
  const hookEventName = stableString(payload.hook_event_name);
  if (!hookEventName) return;

  try {
    if (typeof Bun !== 'undefined' && typeof Bun.spawn === 'function') {
      const subprocess = Bun.spawn([...BRIDGE_BASE_ARGS, '--event', hookEventName], {
        stdin: new Response(JSON.stringify(payload)),
        stdout: 'ignore',
        stderr: 'ignore',
        env: process.env,
      });
      void subprocess.exited.catch(() => {});
      return;
    }

    await forwardViaNode(payload, hookEventName);
  } catch {
    // OpenClaw hooks should never fail because Yorling is unavailable.
  }
};

export default handler;
