[package]
name = "yorling-platform-macos"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yorling-core = { path = "../yorling-core" }
yorling-engine = { path = "../yorling-engine" }
core-foundation = "0.10"
log = "0.4"
libc = "0.2"
objc2 = "0.6.4"
objc2-foundation = { version = "0.3.2", default-features = false, features = ["std", "NSProcessInfo", "NSString", "NSObject"] }
objc2-core-foundation = { version = "0.3.2", default-features = false, features = ["std"] }
objc2-core-video = { version = "0.3.2", default-features = false, features = ["std", "CVBase", "CVReturn", "CVDisplayLink", "objc2-core-graphics"] }
