import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

test('registers the super right click module between music and island', () => {
  const appSource = readFileSync('src/App.tsx', 'utf8');
  const sidebarSource = readFileSync('src/components/common/Sidebar.tsx', 'utf8');
  const typesSource = readFileSync('src/types/index.ts', 'utf8');
  const copySource = readFileSync('src/i18n/copy.ts', 'utf8');

  assert.strictEqual(typesSource.includes("'superRightClick'"), true);
  assert.strictEqual(copySource.includes("superRightClick: '超级右键'"), true);
  assert.strictEqual(copySource.includes("superRightClick: 'Super Right Click'"), true);
  assert.ok(
    sidebarSource.indexOf("{ id: 'music', icon: '♪' }")
      < sidebarSource.indexOf("{ id: 'superRightClick', icon: '⌁' }"),
  );
  assert.ok(
    sidebarSource.indexOf("{ id: 'superRightClick', icon: '⌁' }")
      < sidebarSource.indexOf("{ id: 'island', icon: '◆' }"),
  );
  assert.strictEqual(appSource.includes("case 'superRightClick':"), true);
  assert.strictEqual(appSource.includes('<SuperRightClick />'), true);
});

test('wires super right click through FinderSync without a fallback menu window', () => {
  const appSource = readFileSync('src/App.tsx', 'utf8');
  const componentSource = readFileSync('src/components/super-right-click/SuperRightClick.tsx', 'utf8');
  const copySource = readFileSync('src/i18n/copy.ts', 'utf8');
  const commandSource = readFileSync('src-tauri/src/commands/super_right_click.rs', 'utf8');
  const commandsModSource = readFileSync('src-tauri/src/commands/mod.rs', 'utf8');
  const libSource = readFileSync('src-tauri/src/lib.rs', 'utf8');
  const tauriConfigSource = readFileSync('src-tauri/tauri.conf.json', 'utf8');
  const macosConfigSource = readFileSync('src-tauri/tauri.macos.conf.json', 'utf8');
  const packageSource = readFileSync('package.json', 'utf8');
  const devMacosAppScript = readFileSync('scripts/dev-macos-app.sh', 'utf8');
  const finderSyncSource = readFileSync('src-tauri/macos/YorlingFinderSync/Sources/YorlingFinderSync.swift', 'utf8');
  const finderSyncInfo = readFileSync('src-tauri/macos/YorlingFinderSync/Info.plist', 'utf8');
  const tauriInfo = readFileSync('src-tauri/Info.plist', 'utf8');
  const capabilitySource = readFileSync('src-tauri/capabilities/default.json', 'utf8');
  const styleSource = readFileSync('src/styles/nothing/components.css', 'utf8');

  assert.strictEqual(appSource.includes("label === 'super-right-click-menu'"), false);
  assert.strictEqual(componentSource.includes('SuperRightClickMenuWindow'), false);
  assert.strictEqual(componentSource.includes("listen<SuperRightClickMenuContext>('super-right-click-menu-context'"), false);
  assert.strictEqual(componentSource.includes("invoke<SuperRightClickActionResult>('perform_super_right_click_action'"), false);
  assert.strictEqual(componentSource.includes("invoke<TerminalInventory>('get_terminal_inventory')"), true);
  assert.strictEqual(componentSource.includes("invoke('set_super_right_click_terminal'"), true);
  assert.strictEqual(componentSource.includes("'open_finder_automation_settings'"), true);
  assert.strictEqual(componentSource.includes("'open_accessibility_settings'"), true);
  assert.strictEqual(componentSource.includes('permissionRecoveryTitle'), true);
  assert.strictEqual(componentSource.includes('coverageTitle'), true);
  assert.strictEqual(componentSource.includes('systemEventsPermissionAction'), true);
  assert.strictEqual(componentSource.includes('accessibilitySettingsAction'), true);
  assert.strictEqual(componentSource.includes('super-right-click-mode-panel'), false);
  assert.strictEqual(componentSource.includes('modeTitle'), false);
  assert.strictEqual(componentSource.includes('copy.actionMoveTo'), true);
  assert.strictEqual(commandSource.includes('CGEventTapCreate'), false);
  assert.strictEqual(commandSource.includes('AXUIElementCopyElementAtPosition'), false);
  assert.strictEqual(commandSource.includes('perform_super_right_click_action'), false);
  assert.strictEqual(commandSource.includes('hide_super_right_click_menu'), false);
  assert.strictEqual(commandSource.includes('open_finder_sync_extension_settings'), true);
  assert.strictEqual(commandSource.includes('open_finder_automation_settings'), true);
  assert.strictEqual(commandSource.includes('set_super_right_click_terminal'), true);
  assert.strictEqual(copySource.includes('权限恢复入口'), true);
  assert.strictEqual(copySource.includes('Finder 覆盖范围'), true);
  assert.strictEqual(copySource.includes('Finder Coverage'), true);
  assert.strictEqual(copySource.includes('接入方式'), false);
  assert.strictEqual(copySource.includes('System Events 自动化权限'), true);
  assert.strictEqual(copySource.includes('辅助功能权限'), true);
  assert.strictEqual(copySource.includes('移动到其他文件夹'), true);
  assert.strictEqual(copySource.includes('Move to another folder'), true);
  assert.strictEqual(commandSource.includes('state.enabled = enabled'), true);
  assert.strictEqual(commandSource.includes('super-right-click.json'), true);
  assert.strictEqual(commandSource.includes('runtime_active'), true);
  assert.strictEqual(commandSource.includes('runtime_updated_at'), true);
  assert.strictEqual(commandSource.includes('runtime_lease_is_current'), true);
  assert.strictEqual(commandSource.includes('SHARED_STATE_WRITE_SEQUENCE'), true);
  assert.strictEqual(commandSource.includes('start_super_right_click_runtime_heartbeat'), true);
  assert.strictEqual(commandSource.includes('shutdown_super_right_click_runtime'), true);
  assert.strictEqual(commandSource.includes('start_finder_action_request_worker'), true);
  assert.strictEqual(commandSource.includes('bootstrap_super_right_click_if_enabled'), true);
  assert.strictEqual(commandSource.includes('FINDER_SYNC_BOOTSTRAP_RETRY_DELAYS_MS'), true);
  assert.strictEqual(commandSource.includes('ensure_finder_sync_extension_ready'), true);
  assert.strictEqual(commandSource.includes('wait_for_finder_sync_extension_enabled'), true);
  assert.strictEqual(commandSource.includes('run_pluginkit_command'), true);
  assert.strictEqual(commandSource.includes('FINDER_SYNC_PROCESS_NAME'), true);
  assert.strictEqual(commandSource.includes('has_recent_pending_finder_action_request'), true);
  assert.strictEqual(commandSource.includes('FINDER_ACTION_REQUEST_MAX_AGE_MS'), true);
  assert.strictEqual(commandSource.includes('finder_action_request_is_current'), true);
  assert.strictEqual(commandSource.includes('finder-action-request.json'), true);
  assert.strictEqual(commandSource.includes('toggle_hidden_files_from_main_app'), true);
  assert.strictEqual(commandSource.includes('snap_to_grid_from_main_app'), true);
  assert.strictEqual(commandSource.includes('move_to_folder_from_main_app'), true);
  assert.strictEqual(commandSource.includes('blocking_pick_folder'), false);
  assert.strictEqual(commandSource.includes('choose folder with prompt'), true);
  assert.strictEqual(commandSource.includes('run_independent_apple_script'), true);
  assert.strictEqual(commandSource.includes('display dialog'), true);
  assert.strictEqual(commandSource.includes('move_paths_to_destination'), true);
  assert.strictEqual(commandSource.includes('existing_paths(&request.selected_paths)'), true);
  assert.strictEqual(commandSource.includes('focus_main_window_for_finder_dialog'), false);
  assert.strictEqual(commandSource.includes('unique_move_destination_path'), true);
  assert.strictEqual(commandSource.includes('cannot move into itself'), true);
  assert.strictEqual(commandSource.includes('destination is the same'), true);
  assert.strictEqual(commandSource.includes('Command::new("/bin/mv")'), true);
  assert.strictEqual(commandSource.includes('killall'), false);
  assert.strictEqual(commandSource.includes('update every Finder window'), false);
  assert.strictEqual(commandSource.includes('CGEventCreateKeyboardEvent'), true);
  assert.strictEqual(commandSource.includes('AXIsProcessTrusted'), true);
  assert.strictEqual(commandSource.includes('clean up desktop'), false);
  assert.strictEqual(commandSource.includes('icon view options of desktop'), false);
  assert.strictEqual(commandSource.includes('clean up targetWindow'), false);
  assert.strictEqual(commandSource.includes('clean up front Finder window'), false);
  assert.strictEqual(commandSource.includes('container window of targetFolder'), false);
  assert.strictEqual(commandSource.includes('container window of desktop'), true);
  assert.strictEqual(commandSource.includes('clickFinderSnapToGridSortMode'), true);
  assert.strictEqual(commandSource.includes('tell application "System Events"'), true);
  assert.strictEqual(commandSource.includes('{"排序方式", "Sort By"}'), true);
  assert.strictEqual(commandSource.includes('{"吸附到网格", "Snap to Grid"}'), true);
  assert.strictEqual(commandSource.includes('AXMenuItemMarkChar'), true);
  assert.strictEqual(commandSource.includes('Snap to Grid sort mode did not become checked'), true);
  assert.strictEqual(commandSource.includes('looks_like_accessibility_permission_error'), true);
  assert.strictEqual(commandSource.includes('front Finder window'), true);
  assert.strictEqual(commandSource.includes('repeat with attemptIndex from 1 to 20'), true);
  assert.strictEqual(commandSource.includes('repeat with finderWindowRef in (get Finder windows)'), true);
  assert.strictEqual(commandSource.includes('contents of finderWindowRef'), true);
  assert.strictEqual(commandSource.includes('target of finderWindow as alias'), true);
  assert.strictEqual(commandSource.includes('set index of targetWindow to 1'), true);
  assert.strictEqual(commandSource.includes('icon view options of targetWindow'), true);
  assert.strictEqual(commandSource.includes('set selectedPathList to'), false);
  assert.strictEqual(commandSource.includes('set arrangement of icon view options of workspaceWindow to snap to grid'), false);
  assert.strictEqual(commandSource.includes('set arrangement of icon view options of targetWindow to not arranged'), false);
  assert.strictEqual(commandSource.includes('set arrangement of icon view options of targetWindow to snap to grid'), false);
  assert.strictEqual(commandSource.includes('did not switch to snap to grid'), true);
  assert.strictEqual(commandSource.includes('snapToGrid verified path='), true);
  assert.strictEqual(commandSource.includes('mode=snap-to-grid'), true);
  assert.strictEqual(commandSource.includes('cleanup=window'), false);
  assert.strictEqual(commandSource.includes('rearrange=false'), true);
  assert.strictEqual(commandSource.includes('Finder automation output'), true);
  assert.strictEqual(commandSource.includes('folder_arrangement_directory'), true);
  assert.strictEqual(commandSource.includes('selected_count'), true);
  assert.strictEqual(finderSyncSource.includes('folderArrangementDirectory'), true);
  assert.strictEqual(finderSyncSource.includes('supportsFolderArrangement'), true);
  assert.strictEqual(finderSyncSource.includes('case moveTo'), true);
  assert.strictEqual(finderSyncSource.includes('supportsMoveTo'), true);
  assert.strictEqual(finderSyncSource.includes('movableURLs'), true);
  assert.strictEqual(finderSyncSource.includes('localized("移动到...", "Move To...")'), true);
  assert.strictEqual(finderSyncSource.includes('case .moveTo:'), true);
  assert.strictEqual(finderSyncSource.includes('queueMainAppAction(action, context: context)'), true);
  assert.strictEqual(finderSyncSource.includes('selectedPaths = context.movableURLs.map(\\.path)'), true);
  assert.strictEqual(finderSyncSource.includes('monitoredDirectoryURLs'), true);
  assert.strictEqual(finderSyncSource.includes('URL(fileURLWithPath: "/", isDirectory: true)'), true);
  assert.strictEqual(finderSyncSource.includes('URL(fileURLWithPath: "/Applications", isDirectory: true)'), true);
  assert.strictEqual(finderSyncSource.includes('URL(fileURLWithPath: "/System/Applications", isDirectory: true)'), true);
  assert.strictEqual(finderSyncSource.includes('URL(fileURLWithPath: "/Volumes", isDirectory: true)'), true);
  assert.strictEqual(finderSyncSource.includes('supportsFileActions'), true);
  assert.strictEqual(finderSyncSource.includes('supportsNewFile'), true);
  assert.strictEqual(finderSyncSource.includes('isPackage'), true);
  assert.strictEqual(finderSyncSource.includes('menu using limited actions because Finder did not provide a usable file-system target'), true);
  assert.strictEqual(finderSyncSource.includes('NSOpenPanel()'), false);
  assert.strictEqual(finderSyncSource.includes('if action == .snapToGrid'), true);
  assert.strictEqual(finderSyncSource.includes('selectedPaths = context.selectedItemURLs.map(\\.path)'), true);
  assert.strictEqual(devMacosAppScript.includes('Quitting running Yorling before opening the rebuilt app'), true);
  assert.strictEqual(devMacosAppScript.includes('YORLING_RESTART_RUNNING'), true);
  assert.strictEqual(devMacosAppScript.includes('pluginkit -r "$APPEX_PATH"'), true);
  assert.strictEqual(devMacosAppScript.includes('pkill -x "$FINDER_SYNC_PROCESS_NAME"'), true);
  assert.strictEqual(commandSource.includes('Privacy_Automation'), true);
  assert.strictEqual(commandsModSource.includes('pub mod super_right_click;'), true);
  assert.strictEqual(libSource.includes('SuperRightClickState::new()'), true);
  assert.strictEqual(libSource.includes('Suppressing main window presentation for Finder action launch'), true);
  assert.strictEqual(libSource.includes('commands::super_right_click::bootstrap_super_right_click_if_enabled()'), true);
  assert.strictEqual(libSource.includes('commands::super_right_click::start_super_right_click_runtime_heartbeat()'), true);
  assert.strictEqual(libSource.includes('commands::super_right_click::shutdown_super_right_click_runtime()'), true);
  assert.strictEqual(libSource.includes('commands::super_right_click::start_finder_action_request_worker(app.handle().clone())'), true);
  assert.strictEqual(libSource.includes('commands::super_right_click::start_super_right_click'), true);
  assert.strictEqual(libSource.includes('commands::super_right_click::set_super_right_click_terminal'), true);
  assert.strictEqual(libSource.includes('commands::super_right_click::open_finder_sync_extension_settings'), true);
  assert.strictEqual(libSource.includes('commands::super_right_click::open_finder_automation_settings'), true);
  assert.strictEqual(libSource.includes('commands::keyboard::open_accessibility_settings'), true);
  assert.strictEqual(libSource.includes('commands::super_right_click::perform_super_right_click_action'), false);
  assert.strictEqual(tauriConfigSource.includes('"label": "super-right-click-menu"'), false);
  assert.strictEqual(macosConfigSource.includes('"PlugIns/YorlingFinderSync.appex"'), true);
  assert.strictEqual(macosConfigSource.includes('"target/finder-sync/YorlingFinderSync.appex"'), true);
  assert.strictEqual(packageSource.includes('"build:finder-sync"'), true);
  assert.strictEqual(finderSyncSource.includes('final class YorlingFinderSync: FIFinderSync'), true);
  assert.strictEqual(finderSyncSource.includes('override func menu(for menuKind: FIMenuKind)'), true);
  assert.strictEqual(finderSyncSource.includes('guard isSuperRightClickEnabled() else'), true);
  assert.strictEqual(finderSyncSource.includes('titleToAction'), true);
  assert.strictEqual(finderSyncSource.includes('tagToAction'), true);
  assert.strictEqual(finderSyncSource.includes('resolveAction(from sender: NSMenuItem)'), true);
  assert.strictEqual(finderSyncSource.includes('sender.identifier?.rawValue'), true);
  assert.strictEqual(finderSyncSource.includes('finder-sync-debug.log'), true);
  assert.strictEqual(finderSyncSource.includes('menu.addItem(.separator())'), false);
  assert.strictEqual(finderSyncSource.includes('queueMainAppAction'), true);
  assert.strictEqual(finderSyncSource.includes('DistributedNotificationCenter.default().post'), true);
  assert.strictEqual(finderSyncSource.includes('finder-action-request.json'), true);
  assert.strictEqual(finderSyncSource.includes('containingAppIsRunning()'), true);
  assert.strictEqual(finderSyncSource.includes('appRunning='), true);
  assert.strictEqual(finderSyncSource.includes('selectedTerminalID()'), true);
  assert.strictEqual(finderSyncSource.includes('NSWorkspace.OpenConfiguration'), true);
  assert.strictEqual(finderSyncSource.includes('openApplicationWithArguments'), true);
  assert.strictEqual(finderSyncSource.includes('"--working-directory=\\(directory.path)"'), true);
  assert.strictEqual(finderSyncSource.includes('"/Applications/Ghostty.app/Contents/MacOS/ghostty"'), false);
  assert.strictEqual(finderSyncSource.includes('"/Applications/WezTerm.app/Contents/MacOS/wezterm"'), false);
  assert.strictEqual(finderSyncSource.includes('"/Applications/Alacritty.app/Contents/MacOS/alacritty"'), false);
  assert.strictEqual(finderSyncSource.includes('"/Applications/kitty.app/Contents/MacOS/kitty"'), false);
  assert.strictEqual(finderSyncSource.includes('super-right-click.json'), true);
  assert.strictEqual(finderSyncSource.includes('runtimeLeaseIsCurrent'), true);
  assert.strictEqual(finderSyncSource.includes('runtime_active'), true);
  assert.strictEqual(finderSyncSource.includes('runtime_updated_at'), true);
  assert.strictEqual(JSON.parse(tauriConfigSource).app.windows[0].visible, false);
  assert.strictEqual(finderSyncInfo.includes('com.apple.FinderSync'), true);
  assert.strictEqual(tauriInfo.includes('NSAppleEventsUsageDescription'), true);
  assert.strictEqual(capabilitySource.includes('super-right-click-menu'), false);
  assert.strictEqual(styleSource.includes('.super-right-click-page'), true);
  assert.strictEqual(styleSource.includes('.super-right-click-menu'), false);
});
