/// macOS CGEvent modifier flag masks
pub const FLAG_SHIFT: u64 = 0x00020000; // kCGEventFlagMaskShift
pub const FLAG_CONTROL: u64 = 0x00040000; // kCGEventFlagMaskControl
pub const FLAG_OPTION: u64 = 0x00080000; // kCGEventFlagMaskAlternate
pub const FLAG_COMMAND: u64 = 0x00100000; // kCGEventFlagMaskCommand

/// macOS Virtual Keycodes (Carbon/Events.h kVK_* constants)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum VirtualKeyCode {
    // Letters
    A = 0x00,
    S = 0x01,
    D = 0x02,
    F = 0x03,
    H = 0x04,
    G = 0x05,
    Z = 0x06,
    X = 0x07,
    C = 0x08,
    V = 0x09,
    B = 0x0B,
    Q = 0x0C,
    W = 0x0D,
    E = 0x0E,
    R = 0x0F,
    Y = 0x10,
    T = 0x11,
    O = 0x1F,
    U = 0x20,
    LeftBracket = 0x21,
    I = 0x22,
    P = 0x23,
    L = 0x25,
    J = 0x26,
    RightBracket = 0x1E,
    K = 0x28,
    Semicolon = 0x29,
    Backslash = 0x2A,
    Comma = 0x2B,
    Slash = 0x2C,
    N = 0x2D,
    M = 0x2E,
    Period = 0x2F,
    Minus = 0x1B,
    Equal = 0x18,
    Grave = 0x32,

    // Special
    Return = 0x24,
    Tab = 0x30,
    Space = 0x31,
    Delete = 0x33,
    Escape = 0x35,
    CapsLock = 0x39,

    // Modifiers
    Command = 0x37,
    Shift = 0x38,
    Option = 0x3A,
    Control = 0x3B,
    RightCommand = 0x36,
    RightShift = 0x3C,
    RightOption = 0x3D,
    RightControl = 0x3E,
    Function = 0x3F,

    // Arrow keys
    LeftArrow = 0x7B,
    RightArrow = 0x7C,
    DownArrow = 0x7D,
    UpArrow = 0x7E,
    Home = 0x73,
    End = 0x77,

    // Numbers
    Key0 = 0x1D,
    Key1 = 0x12,
    Key2 = 0x13,
    Key3 = 0x14,
    Key4 = 0x15,
    Key5 = 0x17,
    Key6 = 0x16,
    Key7 = 0x1A,
    Key8 = 0x1C,
    Key9 = 0x19,

    // Function keys
    F1 = 0x7A,
    F2 = 0x78,
    F3 = 0x63,
    F4 = 0x76,
    F5 = 0x60,
    F6 = 0x61,
    F7 = 0x62,
    F8 = 0x64,
    F9 = 0x65,
    F10 = 0x6D,
    F11 = 0x67,
    F12 = 0x6F,
}

impl VirtualKeyCode {
    pub fn from_raw(code: u16) -> Option<Self> {
        match code {
            0x00 => Some(Self::A),
            0x01 => Some(Self::S),
            0x02 => Some(Self::D),
            0x03 => Some(Self::F),
            0x04 => Some(Self::H),
            0x05 => Some(Self::G),
            0x06 => Some(Self::Z),
            0x07 => Some(Self::X),
            0x08 => Some(Self::C),
            0x09 => Some(Self::V),
            0x0B => Some(Self::B),
            0x0C => Some(Self::Q),
            0x0D => Some(Self::W),
            0x0E => Some(Self::E),
            0x0F => Some(Self::R),
            0x10 => Some(Self::Y),
            0x11 => Some(Self::T),
            0x1F => Some(Self::O),
            0x20 => Some(Self::U),
            0x21 => Some(Self::LeftBracket),
            0x22 => Some(Self::I),
            0x23 => Some(Self::P),
            0x25 => Some(Self::L),
            0x26 => Some(Self::J),
            0x1E => Some(Self::RightBracket),
            0x28 => Some(Self::K),
            0x29 => Some(Self::Semicolon),
            0x2A => Some(Self::Backslash),
            0x2B => Some(Self::Comma),
            0x2C => Some(Self::Slash),
            0x2D => Some(Self::N),
            0x2E => Some(Self::M),
            0x2F => Some(Self::Period),
            0x1B => Some(Self::Minus),
            0x18 => Some(Self::Equal),
            0x32 => Some(Self::Grave),
            0x24 => Some(Self::Return),
            0x30 => Some(Self::Tab),
            0x31 => Some(Self::Space),
            0x33 => Some(Self::Delete),
            0x35 => Some(Self::Escape),
            0x39 => Some(Self::CapsLock),
            0x37 => Some(Self::Command),
            0x38 => Some(Self::Shift),
            0x3A => Some(Self::Option),
            0x3B => Some(Self::Control),
            0x36 => Some(Self::RightCommand),
            0x3C => Some(Self::RightShift),
            0x3D => Some(Self::RightOption),
            0x3E => Some(Self::RightControl),
            0x3F => Some(Self::Function),
            0x7B => Some(Self::LeftArrow),
            0x7C => Some(Self::RightArrow),
            0x7D => Some(Self::DownArrow),
            0x7E => Some(Self::UpArrow),
            0x73 => Some(Self::Home),
            0x77 => Some(Self::End),
            0x12 => Some(Self::Key1),
            0x13 => Some(Self::Key2),
            0x14 => Some(Self::Key3),
            0x15 => Some(Self::Key4),
            0x16 => Some(Self::Key6),
            0x17 => Some(Self::Key5),
            0x19 => Some(Self::Key9),
            0x1A => Some(Self::Key7),
            0x1C => Some(Self::Key8),
            0x1D => Some(Self::Key0),
            0x7A => Some(Self::F1),
            0x78 => Some(Self::F2),
            0x63 => Some(Self::F3),
            0x76 => Some(Self::F4),
            0x60 => Some(Self::F5),
            0x61 => Some(Self::F6),
            0x62 => Some(Self::F7),
            0x64 => Some(Self::F8),
            0x65 => Some(Self::F9),
            0x6D => Some(Self::F10),
            0x67 => Some(Self::F11),
            0x6F => Some(Self::F12),
            _ => None,
        }
    }

    pub fn display_name(self) -> &'static str {
        match self {
            Self::A => "A",
            Self::B => "B",
            Self::C => "C",
            Self::D => "D",
            Self::E => "E",
            Self::F => "F",
            Self::G => "G",
            Self::H => "H",
            Self::I => "I",
            Self::J => "J",
            Self::K => "K",
            Self::L => "L",
            Self::M => "M",
            Self::N => "N",
            Self::O => "O",
            Self::P => "P",
            Self::LeftBracket => "[",
            Self::RightBracket => "]",
            Self::Semicolon => ";",
            Self::Backslash => "\\",
            Self::Comma => ",",
            Self::Slash => "/",
            Self::Period => ".",
            Self::Q => "Q",
            Self::R => "R",
            Self::S => "S",
            Self::T => "T",
            Self::U => "U",
            Self::V => "V",
            Self::W => "W",
            Self::X => "X",
            Self::Y => "Y",
            Self::Z => "Z",
            Self::Minus => "-",
            Self::Equal => "=",
            Self::Grave => "`",
            Self::Key0 => "0",
            Self::Key1 => "1",
            Self::Key2 => "2",
            Self::Key3 => "3",
            Self::Key4 => "4",
            Self::Key5 => "5",
            Self::Key6 => "6",
            Self::Key7 => "7",
            Self::Key8 => "8",
            Self::Key9 => "9",
            Self::Return => "Return",
            Self::Tab => "Tab",
            Self::Space => "Space",
            Self::Delete => "Delete",
            Self::Escape => "Esc",
            Self::CapsLock => "CapsLock",
            Self::Command => "⌘",
            Self::Shift => "⇧",
            Self::Option => "⌥",
            Self::Control => "⌃",
            Self::RightCommand => "R⌘",
            Self::RightShift => "R⇧",
            Self::RightOption => "R⌥",
            Self::RightControl => "R⌃",
            Self::Function => "Fn",
            Self::LeftArrow => "←",
            Self::RightArrow => "→",
            Self::DownArrow => "↓",
            Self::UpArrow => "↑",
            Self::Home => "Home",
            Self::End => "End",
            Self::F1 => "F1",
            Self::F2 => "F2",
            Self::F3 => "F3",
            Self::F4 => "F4",
            Self::F5 => "F5",
            Self::F6 => "F6",
            Self::F7 => "F7",
            Self::F8 => "F8",
            Self::F9 => "F9",
            Self::F10 => "F10",
            Self::F11 => "F11",
            Self::F12 => "F12",
        }
    }
}
