import type { MappingRule } from '../../types';

export const defaultRules: MappingRule[] = [
  // === Navigation: Arrow Keys ===
  {
    id: 'nav-j',
    type: 'simple',
    category: 'navigation',
    from: 'J',
    fromDisplay: 'J',
    to: 'LeftArrow',
    toDisplay: '←',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  {
    id: 'nav-k',
    type: 'simple',
    category: 'navigation',
    from: 'K',
    fromDisplay: 'K',
    to: 'DownArrow',
    toDisplay: '↓',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  {
    id: 'nav-i',
    type: 'simple',
    category: 'navigation',
    from: 'I',
    fromDisplay: 'I',
    to: 'UpArrow',
    toDisplay: '↑',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  {
    id: 'nav-l',
    type: 'simple',
    category: 'navigation',
    from: 'L',
    fromDisplay: 'L',
    to: 'RightArrow',
    toDisplay: '→',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  // === Navigation: Word & Line Jump ===
  {
    id: 'nav-h',
    type: 'simple',
    category: 'navigation',
    from: 'H',
    fromDisplay: 'H',
    to: 'Cmd+Left',
    toDisplay: '⌘←',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  {
    id: 'nav-n',
    type: 'simple',
    category: 'navigation',
    from: 'N',
    fromDisplay: 'N',
    to: 'Cmd+Right',
    toDisplay: '⌘→',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  {
    id: 'nav-u',
    type: 'simple',
    category: 'navigation',
    from: 'U',
    fromDisplay: 'U',
    to: 'Option+Left',
    toDisplay: '⌥←',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  {
    id: 'nav-o',
    type: 'simple',
    category: 'navigation',
    from: 'O',
    fromDisplay: 'O',
    to: 'Option+Right',
    toDisplay: '⌥→',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  // === Editing ===
  {
    id: 'edit-q',
    type: 'simple',
    category: 'editing',
    from: 'Q',
    fromDisplay: 'Q',
    to: '4×Space',
    toDisplay: '␣×4',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  {
    id: 'edit-w',
    type: 'simple',
    category: 'editing',
    from: 'W',
    fromDisplay: 'W',
    to: 'Home→Select→Delete',
    toDisplay: '⌘←⇧⌘→⌫',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  {
    id: 'edit-e',
    type: 'simple',
    category: 'editing',
    from: 'E',
    fromDisplay: 'E',
    to: 'Backspace',
    toDisplay: '⌫',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  {
    id: 'edit-r',
    type: 'simple',
    category: 'editing',
    from: 'R',
    fromDisplay: 'R',
    to: 'Option+Backspace',
    toDisplay: '⌥⌫',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  {
    id: 'edit-a',
    type: 'simple',
    category: 'editing',
    from: 'A',
    fromDisplay: 'A',
    to: 'Return',
    toDisplay: '↵',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  {
    id: 'edit-s',
    type: 'simple',
    category: 'editing',
    from: 'S',
    fromDisplay: 'S',
    to: 'Escape',
    toDisplay: '⎋',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  // === System: Tab Switching ===
  {
    id: 'sys-z',
    type: 'simple',
    category: 'system',
    from: 'Z',
    fromDisplay: 'Z',
    to: 'Ctrl+Shift+Tab',
    toDisplay: '⌃⇧⇥',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  {
    id: 'sys-v',
    type: 'simple',
    category: 'system',
    from: 'V',
    fromDisplay: 'V',
    to: 'Ctrl+Tab',
    toDisplay: '⌃⇥',
    modifier: 'Space',
    modifierDisplay: 'Space (hold)',
    active: true,
  },
  // === Number Layer ===
  {
    id: 'num-3-n',
    type: 'simple',
    category: 'number',
    from: 'N',
    fromDisplay: 'N',
    to: '1',
    toDisplay: '1',
    modifier: '3',
    modifierDisplay: '3 (hold)',
    active: true,
  },
  {
    id: 'num-3-m',
    type: 'simple',
    category: 'number',
    from: 'M',
    fromDisplay: 'M',
    to: '2',
    toDisplay: '2',
    modifier: '3',
    modifierDisplay: '3 (hold)',
    active: true,
  },
  {
    id: 'num-3-comma',
    type: 'simple',
    category: 'number',
    from: ',',
    fromDisplay: ',',
    to: '3',
    toDisplay: '3',
    modifier: '3',
    modifierDisplay: '3 (hold)',
    active: true,
  },
  {
    id: 'num-3-j',
    type: 'simple',
    category: 'number',
    from: 'J',
    fromDisplay: 'J',
    to: '4',
    toDisplay: '4',
    modifier: '3',
    modifierDisplay: '3 (hold)',
    active: true,
  },
  {
    id: 'num-3-k',
    type: 'simple',
    category: 'number',
    from: 'K',
    fromDisplay: 'K',
    to: '5',
    toDisplay: '5',
    modifier: '3',
    modifierDisplay: '3 (hold)',
    active: true,
  },
  {
    id: 'num-3-l',
    type: 'simple',
    category: 'number',
    from: 'L',
    fromDisplay: 'L',
    to: '6',
    toDisplay: '6',
    modifier: '3',
    modifierDisplay: '3 (hold)',
    active: true,
  },
  {
    id: 'num-3-u',
    type: 'simple',
    category: 'number',
    from: 'U',
    fromDisplay: 'U',
    to: '7',
    toDisplay: '7',
    modifier: '3',
    modifierDisplay: '3 (hold)',
    active: true,
  },
  {
    id: 'num-3-i',
    type: 'simple',
    category: 'number',
    from: 'I',
    fromDisplay: 'I',
    to: '8',
    toDisplay: '8',
    modifier: '3',
    modifierDisplay: '3 (hold)',
    active: true,
  },
  {
    id: 'num-3-o',
    type: 'simple',
    category: 'number',
    from: 'O',
    fromDisplay: 'O',
    to: '9',
    toDisplay: '9',
    modifier: '3',
    modifierDisplay: '3 (hold)',
    active: true,
  },
  {
    id: 'num-3-b',
    type: 'simple',
    category: 'number',
    from: 'B',
    fromDisplay: 'B',
    to: '0',
    toDisplay: '0',
    modifier: '3',
    modifierDisplay: '3 (hold)',
    active: true,
  },
  {
    id: 'num-3-h',
    type: 'simple',
    category: 'number',
    from: 'H',
    fromDisplay: 'H',
    to: '0',
    toDisplay: '0',
    modifier: '3',
    modifierDisplay: '3 (hold)',
    active: true,
  },
  // === Symbol Layer ===
  {
    id: 'sym-semicolon-tap-round',
    type: 'simple',
    category: 'symbol',
    from: 'X then K',
    fromDisplay: 'XK',
    to: '()',
    toDisplay: '()',
    modifier: '; (tap)',
    modifierDisplay: '; (tap)',
    active: true,
  },
  {
    id: 'sym-semicolon-tap-square',
    type: 'simple',
    category: 'symbol',
    from: 'Z then K',
    fromDisplay: 'ZK',
    to: '[]',
    toDisplay: '[]',
    modifier: '; (tap)',
    modifierDisplay: '; (tap)',
    active: true,
  },
  {
    id: 'sym-semicolon-tap-curly',
    type: 'simple',
    category: 'symbol',
    from: 'D then K',
    fromDisplay: 'DK',
    to: '{}',
    toDisplay: '{}',
    modifier: '; (tap)',
    modifierDisplay: '; (tap)',
    active: true,
  },
  {
    id: 'sym-semicolon-a',
    type: 'simple',
    category: 'symbol',
    from: 'A',
    fromDisplay: 'A',
    to: '-',
    toDisplay: '-',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-b',
    type: 'simple',
    category: 'symbol',
    from: 'B',
    fromDisplay: 'B',
    to: '%',
    toDisplay: '%',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-c',
    type: 'simple',
    category: 'symbol',
    from: 'C',
    fromDisplay: 'C',
    to: '.',
    toDisplay: '.',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-d',
    type: 'simple',
    category: 'symbol',
    from: 'D',
    fromDisplay: 'D',
    to: '=',
    toDisplay: '=',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-e',
    type: 'simple',
    category: 'symbol',
    from: 'E',
    fromDisplay: 'E',
    to: '^',
    toDisplay: '^',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-f',
    type: 'simple',
    category: 'symbol',
    from: 'F',
    fromDisplay: 'F',
    to: '>',
    toDisplay: '>',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-g',
    type: 'simple',
    category: 'symbol',
    from: 'G',
    fromDisplay: 'G',
    to: '!',
    toDisplay: '!',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-h',
    type: 'simple',
    category: 'symbol',
    from: 'H',
    fromDisplay: 'H',
    to: '+',
    toDisplay: '+',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-i',
    type: 'simple',
    category: 'symbol',
    from: 'I',
    fromDisplay: 'I',
    to: ':',
    toDisplay: ':',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-j',
    type: 'simple',
    category: 'symbol',
    from: 'J',
    fromDisplay: 'J',
    to: ';',
    toDisplay: ';',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-k',
    type: 'simple',
    category: 'symbol',
    from: 'K',
    fromDisplay: 'K',
    to: '`',
    toDisplay: '`',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-n',
    type: 'simple',
    category: 'symbol',
    from: 'N',
    fromDisplay: 'N',
    to: '/',
    toDisplay: '/',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-q',
    type: 'simple',
    category: 'symbol',
    from: 'Q',
    fromDisplay: 'Q',
    to: '-',
    toDisplay: '-',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-r',
    type: 'simple',
    category: 'symbol',
    from: 'R',
    fromDisplay: 'R',
    to: '&',
    toDisplay: '&',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-s',
    type: 'simple',
    category: 'symbol',
    from: 'S',
    fromDisplay: 'S',
    to: '<',
    toDisplay: '<',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-t',
    type: 'simple',
    category: 'symbol',
    from: 'T',
    fromDisplay: 'T',
    to: '~',
    toDisplay: '~',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-u',
    type: 'simple',
    category: 'symbol',
    from: 'U',
    fromDisplay: 'U',
    to: '$',
    toDisplay: '$',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-v',
    type: 'simple',
    category: 'symbol',
    from: 'V',
    fromDisplay: 'V',
    to: '|',
    toDisplay: '|',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-w',
    type: 'simple',
    category: 'symbol',
    from: 'W',
    fromDisplay: 'W',
    to: '#',
    toDisplay: '#',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-x',
    type: 'simple',
    category: 'symbol',
    from: 'X',
    fromDisplay: 'X',
    to: '_',
    toDisplay: '_',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-y',
    type: 'simple',
    category: 'symbol',
    from: 'Y',
    fromDisplay: 'Y',
    to: '@',
    toDisplay: '@',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  {
    id: 'sym-semicolon-z',
    type: 'simple',
    category: 'symbol',
    from: 'Z',
    fromDisplay: 'Z',
    to: '\\',
    toDisplay: '\\',
    modifier: ';',
    modifierDisplay: '; (hold)',
    active: true,
  },
  // === Mouse Layer ===
  {
    id: 'mouse-tab-j',
    type: 'simple',
    category: 'mouse',
    from: 'J',
    fromDisplay: 'J',
    to: 'Mouse Left',
    toDisplay: '←',
    modifier: 'Tab',
    modifierDisplay: 'Tab (hold)',
    active: true,
  },
  {
    id: 'mouse-tab-k',
    type: 'simple',
    category: 'mouse',
    from: 'K',
    fromDisplay: 'K',
    to: 'Mouse Down',
    toDisplay: '↓',
    modifier: 'Tab',
    modifierDisplay: 'Tab (hold)',
    active: true,
  },
  {
    id: 'mouse-tab-i',
    type: 'simple',
    category: 'mouse',
    from: 'I',
    fromDisplay: 'I',
    to: 'Mouse Up',
    toDisplay: '↑',
    modifier: 'Tab',
    modifierDisplay: 'Tab (hold)',
    active: true,
  },
  {
    id: 'mouse-tab-l',
    type: 'simple',
    category: 'mouse',
    from: 'L',
    fromDisplay: 'L',
    to: 'Mouse Right',
    toDisplay: '→',
    modifier: 'Tab',
    modifierDisplay: 'Tab (hold)',
    active: true,
  },
  {
    id: 'mouse-tab-u',
    type: 'simple',
    category: 'mouse',
    from: 'U',
    fromDisplay: 'U',
    to: 'Scroll Up',
    toDisplay: '⇡',
    modifier: 'Tab',
    modifierDisplay: 'Tab (hold)',
    active: true,
  },
  {
    id: 'mouse-tab-o',
    type: 'simple',
    category: 'mouse',
    from: 'O',
    fromDisplay: 'O',
    to: 'Scroll Down',
    toDisplay: '⇣',
    modifier: 'Tab',
    modifierDisplay: 'Tab (hold)',
    active: true,
  },
  {
    id: 'mouse-tab-r',
    type: 'simple',
    category: 'mouse',
    from: 'R',
    fromDisplay: 'R',
    to: 'Mouse Back',
    toDisplay: 'Back',
    modifier: 'Tab',
    modifierDisplay: 'Tab (hold)',
    active: true,
  },
  {
    id: 'mouse-tab-c',
    type: 'simple',
    category: 'mouse',
    from: 'C',
    fromDisplay: 'C',
    to: 'Cmd+[',
    toDisplay: '⌘[',
    modifier: 'Tab',
    modifierDisplay: 'Tab (hold)',
    active: true,
  },
  {
    id: 'mouse-tab-n',
    type: 'simple',
    category: 'mouse',
    from: 'N',
    fromDisplay: 'N',
    to: 'Left Click',
    toDisplay: 'L Click',
    modifier: 'Tab',
    modifierDisplay: 'Tab (hold)',
    active: true,
  },
  {
    id: 'mouse-tab-m',
    type: 'simple',
    category: 'mouse',
    from: 'M',
    fromDisplay: 'M',
    to: 'Right Click',
    toDisplay: 'R Click',
    modifier: 'Tab',
    modifierDisplay: 'Tab (hold)',
    active: true,
  },
  // === Windows Shortcuts ===
  {
    id: 'win-ctrl-c',
    type: 'simple',
    category: 'shortcut',
    from: 'C',
    fromDisplay: 'C',
    to: 'Cmd+C',
    toDisplay: '⌘C',
    modifier: 'Ctrl',
    modifierDisplay: 'Ctrl',
    active: true,
  },
  {
    id: 'win-ctrl-v',
    type: 'simple',
    category: 'shortcut',
    from: 'V',
    fromDisplay: 'V',
    to: 'Cmd+V',
    toDisplay: '⌘V',
    modifier: 'Ctrl',
    modifierDisplay: 'Ctrl',
    active: true,
  },
  {
    id: 'win-ctrl-x',
    type: 'simple',
    category: 'shortcut',
    from: 'X',
    fromDisplay: 'X',
    to: 'Cmd+X',
    toDisplay: '⌘X',
    modifier: 'Ctrl',
    modifierDisplay: 'Ctrl',
    active: true,
  },
  {
    id: 'win-ctrl-s',
    type: 'simple',
    category: 'shortcut',
    from: 'S',
    fromDisplay: 'S',
    to: 'Cmd+S',
    toDisplay: '⌘S',
    modifier: 'Ctrl',
    modifierDisplay: 'Ctrl',
    active: true,
  },
  {
    id: 'win-shift-screenshot',
    type: 'simple',
    category: 'shortcut',
    from: 'S',
    fromDisplay: 'S',
    to: 'Cmd+Shift+4',
    toDisplay: '⌘⇧4',
    modifier: 'Win+Shift',
    modifierDisplay: 'Win+Shift',
    active: true,
  },
  {
    id: 'win-ctrl-z',
    type: 'simple',
    category: 'shortcut',
    from: 'Z',
    fromDisplay: 'Z',
    to: 'Cmd+Z',
    toDisplay: '⌘Z',
    modifier: 'Ctrl',
    modifierDisplay: 'Ctrl',
    active: true,
  },
  {
    id: 'win-ctrl-a',
    type: 'simple',
    category: 'shortcut',
    from: 'A',
    fromDisplay: 'A',
    to: 'Cmd+A',
    toDisplay: '⌘A',
    modifier: 'Ctrl',
    modifierDisplay: 'Ctrl',
    active: true,
  },
  {
    id: 'win-alt-tab',
    type: 'simple',
    category: 'shortcut',
    from: 'Tab',
    fromDisplay: 'Tab',
    to: 'Window Switcher',
    toDisplay: '窗口切换',
    modifier: 'Alt',
    modifierDisplay: 'Alt',
    active: true,
  },
];
